version: "2.4"
services:
  jenkins:
    build: ./jenkins_controller/
    container_name: jenkins_controller
    ports:
      - "50000:50000"
      - "8880:8080"
    restart: always
    volumes:
    - ./jenkins_controller/jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml

  sonarqube:
    image: sonarqube:10.2.1-community
    container_name: sonarqube
    depends_on: 
      - jenkins
    ports:
      - "9000:9000"
    restart: always

  selenium_hub:
    depends_on:
      - jenkins
    image: selenium/hub
    container_name: selenium_hub
    ports:
    - "4442:4442"
    - "4443:4443"
    - "4444:4444"
    restart: always
